version: '3'
services:
  wordpress:
    image: wordpress
    ports:
      - "8005:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpressUSER
      WORDPRESS_DB_PASSWORD: riki
      WORDPRESS_DB_NAME: wordpressDB
    volumes:
      - ./wp-content:/var/www/html/wp-content

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpressDB
      MYSQL_USER: wordpressUSER
      MYSQL_PASSWORD: riki
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8006:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: riki

volumes:
  db_data:
